services:
#  ${BACKEND_SERVICE_NAME}:
#    image: myuser/java-app:latest
#    networks:
#      - appalanche-net

  frontend:
    image: 'andrej-ziv/appalanche-vue-frontend:latest'
    container_name: app_frontend
    environment:
      - BACKEND_SERVICE_NAME=${BACKEND_SERVICE_NAME}
      - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
#    depends_on:
#      - ${BACKEND_SERVICE_NAME}
    networks:
      - appalanche-net